package com.nearaid.core.database

import androidx.room.ConstructedBy
import androidx.room.Database
import androidx.room.RoomDatabase
import androidx.room.RoomDatabaseConstructor
import com.nearaid.core.database.dao.ConversationCacheDao
import com.nearaid.core.database.dao.ListingCacheDao
import com.nearaid.core.database.entity.CachedConversationEntity
import com.nearaid.core.database.entity.CachedListingEntity

@Database(
    entities = [CachedListingEntity::class, CachedConversationEntity::class],
    version = 1,
    exportSchema = true,
)
@ConstructedBy(NearAidDatabaseConstructor::class)
abstract class NearAidDatabase : RoomDatabase() {
    abstract fun listingCacheDao(): ListingCacheDao
    abstract fun conversationCacheDao(): ConversationCacheDao
}

// Room-KMP requires this expect object; the `actual` is generated by the Room compiler
// per target. The IDE flags "expect with no actual" — that is expected here (suppressed).
@Suppress("KotlinNoActualForExpectDeclaration", "NO_ACTUAL_FOR_EXPECT")
expect object NearAidDatabaseConstructor : RoomDatabaseConstructor<NearAidDatabase> {
    override fun initialize(): NearAidDatabase
}
